name: manual event
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch name'
        required: true
        default: 'main'
      name:
        description: 'your name'
        required: false
        default: 'Victor'
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch ${{ github.event.inputs.branch }} - your name: ${{ github.event.inputs.name }}
