name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      password:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Show inputs and secrets
    runs-on: ubuntu-latest
    steps:
      - name: echo inputs and secrets
        run: echo username - ${{ inputs.username }} password - ${{ inputs.password }} token - ${{ secrets.token }}
